"""added geometry_id

Revision ID: 6261e60a0a73
Revises: e1ac5aa68b6b
Create Date: 2024-06-02 21:58:27.486682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6261e60a0a73"
down_revision: Union[str, None] = "e1ac5aa68b6b"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "geometries_feature_id_fkey",
        "geometries",
        type_="foreignkey",
    )
    op.drop_column("geometries", "feature_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geometries",
        sa.Column(
            "feature_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "geometries_feature_id_fkey",
        "geometries",
        "features",
        ["feature_id"],
        ["id"],
    )
    # ### end Alembic commands ###
