"""added geometry_id

Revision ID: e1ac5aa68b6b
Revises: fbed0283c21f
Create Date: 2024-06-02 21:52:15.456847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1ac5aa68b6b"
down_revision: Union[str, None] = "fbed0283c21f"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "features",
        sa.Column(
            "geometry_id",
            sa.UUID(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "features",
        "geometries",
        ["geometry_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "features", type_="foreignkey"
    )
    op.drop_column("features", "geometry_id")
    # ### end Alembic commands ###
